components:
  schemas:
    Price:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        currency:
          type: string
        channelId:
          type: string
        createdAt:
          type: string
          format: date-time
      required: [name, channelId, currency]

    PriceSetting:
      type: object
      properties:
        id:
          type: string
        priceId:
          type: string
        feeType:
          type: string
        value:
          type: number
        expression:
          type: array
          items:
            type: object
        note:
          type: string
      required: [priceId, feeType, value]
