version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fba_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: yujiacheng
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fba_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
